// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package resource

import "reflect"

var Types = map[string]reflect.Type{
	"Announcement":            reflect.TypeOf((*Announcement)(nil)).Elem(),
	"AuthTest":                reflect.TypeOf((*AuthTest)(nil)).Elem(),
	"Backers":                 reflect.TypeOf((*Backers)(nil)).Elem(),
	"Connection":              reflect.TypeOf((*Connection)(nil)).Elem(),
	"Dataset":                 reflect.TypeOf((*Dataset)(nil)).Elem(),
	"Disturbance":             reflect.TypeOf((*Disturbance)(nil)).Elem(),
	"DisturbanceReport":       reflect.TypeOf((*DisturbanceReport)(nil)).Elem(),
	"Feedback":                reflect.TypeOf((*Feedback)(nil)).Elem(),
	"Gateway":                 reflect.TypeOf((*Gateway)(nil)).Elem(),
	"Line":                    reflect.TypeOf((*Line)(nil)).Elem(),
	"LineCondition":           reflect.TypeOf((*LineCondition)(nil)).Elem(),
	"Lobby":                   reflect.TypeOf((*Lobby)(nil)).Elem(),
	"MQTTGatewayInfoProvider": reflect.TypeOf((*MQTTGatewayInfoProvider)(nil)).Elem(),
	"Map":                     reflect.TypeOf((*Map)(nil)).Elem(),
	"Meta":                    reflect.TypeOf((*Meta)(nil)).Elem(),
	"Network":                 reflect.TypeOf((*Network)(nil)).Elem(),
	"POI":                     reflect.TypeOf((*POI)(nil)).Elem(),
	"Pair":                    reflect.TypeOf((*Pair)(nil)).Elem(),
	"PairConnection":          reflect.TypeOf((*PairConnection)(nil)).Elem(),
	"PairConnectionHandler":   reflect.TypeOf((*PairConnectionHandler)(nil)).Elem(),
	"Realtime":                reflect.TypeOf((*Realtime)(nil)).Elem(),
	"RealtimeStatsHandler":    reflect.TypeOf((*RealtimeStatsHandler)(nil)).Elem(),
	"RealtimeVehicleHandler":  reflect.TypeOf((*RealtimeVehicleHandler)(nil)).Elem(),
	"ReportHandler":           reflect.TypeOf((*ReportHandler)(nil)).Elem(),
	"Station":                 reflect.TypeOf((*Station)(nil)).Elem(),
	"Stats":                   reflect.TypeOf((*Stats)(nil)).Elem(),
	"StatsCalculator":         reflect.TypeOf((*StatsCalculator)(nil)).Elem(),
	"Transfer":                reflect.TypeOf((*Transfer)(nil)).Elem(),
	"Trip":                    reflect.TypeOf((*Trip)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"ClearMOTD":                     reflect.ValueOf(ClearMOTD),
	"RegisterPairConnectionHandler": reflect.ValueOf(RegisterPairConnectionHandler),
	"RenderData":                    reflect.ValueOf(RenderData),
	"RenderMsgpack":                 reflect.ValueOf(RenderMsgpack),
	"RenderUnauthorized":            reflect.ValueOf(RenderUnauthorized),
	"SetMOTDHTML":                   reflect.ValueOf(SetMOTDHTML),
	"SetMOTDHTMLForLocale":          reflect.ValueOf(SetMOTDHTMLForLocale),
	"SetMOTDMainLocale":             reflect.ValueOf(SetMOTDMainLocale),
	"SetMOTDPriority":               reflect.ValueOf(SetMOTDPriority),
}

var Variables = map[string]reflect.Value{
	"EnableMQTTGateway": reflect.ValueOf(&EnableMQTTGateway),
}

var Consts = map[string]reflect.Value{}
